Tests done
AssortedCaret/java-filmorate pull request #4
Opened 2023-02-19 09:16 UTC by AssortedCaret

2023-02-19 19:06 UTC, AssortedCaret commented
Совсем не понимаю что от меня тут требуется и где именно закралась ошибка, подскажите, пожалуйста

2023-02-20 07:27 UTC, AssortedCaret commented
Разобрался, косяк с тестами, они и так не очень сделаны, буду доделывать

2023-02-20 14:55 UTC, zgreen3 commented
> Совсем не понимаю что от меня тут требуется и где именно закралась ошибка, подскажите, пожалуйста
"Надо исправить":
На будущее: в таких ситуациях (когда pull-request не проходит внешние авто-проверку / авто-тесты, написанные Яндекс.Практикумом) важно обращаться за помощью к наставнику, поскольку у ревьюеров с 9 спринта есть возможность делать code-review только проектов, в которых авто-тесты уже успешно пройдены.

В данной ситуации можем сделать исключение и я посмотрю сегодня работу в том виде, в котором она есть сейчас. Но в будущем я так не смогу делать, потому что в процессе исправления работы для того, чтобы она прошла внешние авто-тесты, её код вероятно может сильно измениться и это потребовало бы перепроверки со стороны код-ревьюера, что не экономит ни время студента, ни ревьюера =().

Здесь, чтобы проект запускался для автотестов также нужно, чтобы написанные тобой тесты успешно отрабатывали. Для этого 
1. или нужно убрать аннотацию "@SpringBootTest" (насколько помню, к 9-му спринту вы, всё равно, ещё не проходили детали работы этой аннотации, пройдёте далее) из классов FIlmControllerTest и UserControllerTest, 

2. или изменить путь до файлов с этими классами (считая от корня проекта) с "ru/yandex/practicum/filmorate/test/" на "ru/yandex/practicum/filmorate/controller/".

2023-02-20 18:00 UTC, AssortedCaret commented
Тесты сделал, если честно маленько запутался, но хватило ума посмотреть QA Иванова и вроде более менее разобрался, единственное не до конца понятно: зачем делать тесты отдельные, если мы в принципе в постмане всё проверяем? Или постман в данном случае больше к тестировщикам относится?

2023-02-20 19:25 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично. 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на продолжение проверки.
Спасибо.

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty
"Можно лучше":
Три аннотации для валидации здесь одновременно избыточны, т.к. по их документации, @NotEmpty и @NotBlank включают в себя проверку на null. Предлагаю оставить здесь аннотацию @NotBlank , чтобы соответствовать ТЗ и обеспечить максимум полезных проверок одной аннотацией для данной ситуации.

Также можно добавить дефолтное сообщение при несоблюдении данного ограничения валидации, например:
`@NotBlank(message = "Название фильма не должно быть пустым")`

(Аналогичный комментарий относится к классу User)

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
"Можно лучше":
Проверку условия ТЗ о том, что "максимальная длина описания — 200 символов", есть возможность также провести на уровне модели (что, вероятно, несколько проще для написания и последующей поддержки кода), используя аннотацию
`@Size(min = 1, max = 200)`.
(см. детали, например, в этой документации https://jakarta.ee/specifications/bean-validation/3.0/apidocs/).

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private  String login;
"Надо исправить":
В соответствии с ТЗ логин не должен содержать пробелов ("внутри" текста), поэтому важно добавить эту проверку в код, или в метод валидации контроллера, или, например, такой аннотацией над данным полем логина: `@Pattern(regexp = "\\S*", message = "Логин не должен содержать пробелов")`.

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.debug("Не выполнены условия добавления пользователя. Пользователь не добавлен");
"Можно лучше" (иначе):
В зависимости от договорённостей внутри команды на проекте, а также инфраструктуры проекта (которую в крупных проектах делает отдельная команда DevOps), может потребоваться сразу указывать в случае ошибок уровень логирования `log.error(...)`, чтобы данные об ошибке, например, сохранялись на сервере в папке для таких логов и потом мониторились отдельными инструментами.

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Отлично:
Отлично, что ты используешь здесь библиотеку slf4j для логирования и аннотацию @Slf4j библиотеки Lombok, чтобы не создавать логгер вручную!

2023-02-20 19:25 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Отлично:
Отлично, что ты используешь здесь аннотация `@Data` библиотеки Lombok, т.к. с ней нужно проделывать меньше работы по созданию сущностей =) (при этом такой подход - не панацея, т.к. у Ломбока есть свои тонкие недостатки, например, рост времени компиляции приложений на порядок, если использовать ряд аннотаций Ломбок, требующих от его препроцессора значительной работы и т.п., это стоит также иметь ввиду и уметь писать нужные методы руками, а также внимательно изучать документацию этой библиотеки для понимания, какой код она неявно привносит в приложение).

2023-02-20 19:30 UTC, zgreen3 commented
> Тесты сделал, если честно маленько запутался, но хватило ума посмотреть QA Иванова и вроде более менее разобрался, единственное не до конца понятно: зачем делать тесты отдельные, если мы в принципе в постмане всё проверяем? Или постман в данном случае больше к тестировщикам относится?

Всё так, постман - это внешний способ проверки по отношению к нашему проекту (обычно его используют бэкенд-разработчики для отладки, а QA для smoke-тестов, интеграционных тестов, API (UI) тестов и т.п. .
А юнит-тесты обычно всегда пишут сами разработчики, и не только на методы контроллеров. В данном спринте это не очень наглядно, согласен, но потом вы добавите юнит-тесты на другие классы, которые через Postman прямо не протестировать.

2023-02-24 06:38 UTC, johnskyi commented on UserControllerTest.java
> +    public void shouldBeFullUser(){
аннотации @Test  не хватает и все аналогично комментарию выше

2023-02-24 06:38 UTC, johnskyi commented on FIlmControllerTest.java
> +    public void shouldBeFullFilm(){
в чем смысл этого теста? Нужно протестировать валидацию. т.е. создаете объект с заведомо невалидными параметрами, передаете в контроллер и ловите исключение

2023-02-24 06:38 UTC, johnskyi commented on FIlmControllerTest.java
> +   // @Test
@Autowired private final FilmController filmcontroller

2023-02-24 06:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    HashMap<Integer, Film> films = new HashMap<Integer, Film>();
private final

2023-02-24 06:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    HashMap<Integer, User> users = new HashMap<Integer, User>();
private final

2023-02-24 06:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private int putIdUser(User user){
приватный метод стоит спустить в самый низ класса после всех публичных

2023-02-24 06:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validateUser(@Valid User user) throws ValidationException {
и этот тоже

2023-02-24 06:38 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
@NotEmpty на стринговыми переменными лучше не ставить, здесь @NotBlank достаточно

2023-02-24 06:38 UTC, johnskyi commented on test/java/test/UserControllerTest.java
> +    public void shouldBeFullUser(){
смысл этого теста тоже непонятен

2023-02-26 08:50 UTC, AssortedCaret commented on test/java/test/UserControllerTest.java
> +    public void shouldBeFullUser(){
Тесты переделал в соответствии с QA Иванова, если всё же не верно, то ещё раз переделаю

2023-02-26 09:27 UTC, closed without merging