ТЗ 10 1 попытка
AssortedCaret/java-filmorate pull request #6
Opened 2023-03-17 20:20 UTC by AssortedCaret

2023-03-18 20:24 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично. 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на продолжение проверки.
Спасибо.

2023-03-18 20:24 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public HashMap getMap(){
Надо исправить:
Нужно параметризовать тип возвращаемого значения, т.к. только тогда при использовании данного метода другими методами ещё на этапе комипляции проекта будет осуществлена проверка типов для возвращаемого значения, иначе компилятору пришлось бы считать тип элементов возвращаемой хеш-таблицы как тип Object.

Можно лучше:
Открытие деталей реализации хранилища для классов уровня сервисов - это, хотя технически польностью допустимое действие, с т.з. архитектуры приложения приводит к излишнему связыванию между классами DAO / хранилища и классами сервисов, например, классом сервиса для фильмов. Для целей дальнейшего (возможного, особенно со следующего, 11 спринта) рефакторинга кода будет важно возвращать / использовать на слое сервисов только уже открытые (т.е. public) методы данного класса хранилища, но не данный.

2023-03-18 20:24 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Нужно исправить:
С т.з. ООП и перспектив возможного рефакторинга кода, а также в соответствии с ТЗ ("Убедитесь, что сервисы зависят от интерфейсов классов-хранилищ, а не их реализаций") важно, чтобы сервисы зависели от интерфейсов классов-хранилищ, а не их реализаций, т.е. здесь тип поля целесообразнее указать как FilmStorage (в IDE обычно встроена возможность глобального, по всему коду, переименования поля и т.п.):
`private final FilmStorage filmStorage;`


Аналогичный комментарий справедлив для класса хранилища пользователей.

2023-03-18 20:24 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.inMemoryFilmStorage = inMemoryFilmStorage;
Можно лучше:
С т.з. трёёхзвенной (в т.ч. ООП) архитектуры приложения важно, чтобы слой хранилищ вовсе не был известен контроллеру, контроллер использует для обработки внешних запросов только слой сервиса.

2023-03-18 20:24 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilmById(@PathVariable("id") Integer id) {
Отлично:
Отлично, что ты понимаешь разницу между @RequestParam и @PathVariable (кстати, см. небольшое напоминание об их отличиях, на англ. яз., здесь: https://stackoverflow.com/a/13718502)!

2023-03-18 20:24 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +public class ErrorHandler {
Отлично:
Отлично, что ты корректно реализовал класс с @ExceptionHandler-ами для централизованной обработки ошибок!

2023-03-18 21:29 UTC, AssortedCaret commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return film.get(Math.toIntExact(id - 1));
У меня изначально был везде тип Лонг и при изменении на Integer было необходимо вставить эту проверку, сейчас её убрал, необходимость в ней пропала, везде Integer

2023-03-18 21:55 UTC, AssortedCaret commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.inMemoryFilmStorage = inMemoryFilmStorage;
То есть необходимо перевести все методы из хранилища в сервис(чтобы их можно было вызывать через сервис)?

2023-03-19 12:17 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-03-19 12:17 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.inMemoryFilmStorage = inMemoryFilmStorage;
Почти (т.к. не совсем все)): можно создать в сервисе недостающие методы, которые уже будут в своей реализации в сервисе вызывать методы хранилища (используемые в твоём коде контроллера напрямую из хранилища), т.е. можно создать в классе сервиса методы getFilm(id), getFilms(), addFilm(film), updateFIlm(film), которые внутри себя будут вызывать соответствующие методы хранилища.

Обращаю внимание, что это был комментарий "Можно лучше", который достаточно принять во внимание, а реализацию сделать уже в спринте 11, например (особенно, если дедлайн близко=())).

2023-03-21 20:16 UTC, merged